
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmRoomInfoSearch.java
 *
 * Created on May 10, 2017, 11:55:58 AM
 */

/**
 *
 * @author PC 20
 */
public class frmPatntRgsSearch extends javax.swing.JFrame {

    /** Creates new form frmRoomInfoSearch */
    public frmPatntRgsSearch() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_ptntslct = new javax.swing.JComboBox();
        b_go = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_rmpatntrgsrch = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Patient");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel1.setText("Search Patient");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 20, 320, 60);

        cmb_ptntslct.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cmb_ptntslct.setModel(new DefaultComboBoxModel());
        cmb_ptntslct.setOpaque(false);
        getContentPane().add(cmb_ptntslct);
        cmb_ptntslct.setBounds(320, 100, 188, 40);

        b_go.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        b_go.setText("Go...!!!");
        b_go.setOpaque(false);
        b_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_goActionPerformed(evt);
            }
        });
        getContentPane().add(b_go);
        b_go.setBounds(590, 90, 140, 50);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 600);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 0, 600);

        tbl_rmpatntrgsrch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tbl_rmpatntrgsrch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Address ", "Contact Number", "Disease", "Room No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_rmpatntrgsrch.setOpaque(false);
        jScrollPane2.setViewportView(tbl_rmpatntrgsrch);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 200, 790, 160);

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel5.setText("Select Patient");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 100, 171, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAMSUNG\\Documents\\NetBeansProjects\\HMS\\HMS 28 dec\\HMS_&\\projct OMAGES\\patient registration search2.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-6, 0, 910, 550);

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel6.setText("Select Patient");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 100, 171, 30);

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel7.setText("Select Patient");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 100, 171, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection con=null;
    Statement stmt=null;
    String dr="java.sql.Driver";
   String url="jdbc:mysql://localhost:3306/hms?zeroDateTimeBehavior=convertToNull";
    String usr="root";
    String pwd="";
    String qry="";
    ResultSet rs=null;
    ResultSet rsPat=null;
    private void b_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_goActionPerformed
        // TODO add your handling code here:

         try{
             
             Class.forName(dr);
             con=DriverManager.getConnection(url, usr, pwd);
             stmt=con.createStatement();
          qry="select  PatNm, Gndr,Addr,ContNbr,DisNm,RoomNbr from registration,RoomInfo where Registration.RoomId=RoomInfo.RoomID and PatNm= '"+cmb_ptntslct.getSelectedItem()+"'";
        rs=stmt.executeQuery(qry);
        DefaultTableModel mdl=(DefaultTableModel)tbl_rmpatntrgsrch.getModel();
        mdl.setRowCount(0);
        while(rs.next())
                 mdl.addRow(new Object[]{ rs.getString("PatNm"), rs.getString("Gndr"),rs.getString("Addr"),rs.getString("ContNbr"), rs.getString("DisNm") , rs.getString("RoomNbr")});
       
         }catch(Exception e){
       
             JOptionPane.showMessageDialog(rootPane, "failed" + e);
       }
        
    }//GEN-LAST:event_b_goActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setBounds(250, 120, 900, 545);
        try{
             
             Class.forName(dr);
             con=DriverManager.getConnection(url, usr, pwd);
             stmt=con.createStatement();
             qry="Select PatNm from Registration";
             rsPat=stmt.executeQuery(qry);
             DefaultComboBoxModel cmdl=(DefaultComboBoxModel)cmb_ptntslct.getModel();
        while (rsPat.next())
            cmdl.addElement(rsPat.getString("PatNm")+"");
        
       cmdl.insertElementAt("--Select--", 0);
       cmb_ptntslct.setSelectedIndex(0);
        
        qry="select  PatNm, Gndr,Addr,ContNbr,DisNm,RoomNbr from registration,RoomInfo where Registration.RoomId=RoomInfo.RoomID";
        rs=stmt.executeQuery(qry);
        while(rs.next())
       {
         DefaultTableModel mdl=(DefaultTableModel)tbl_rmpatntrgsrch.getModel();
        mdl.addRow(new Object[]{ rs.getString("PatNm"), rs.getString("Gndr"),rs.getString("Addr"),rs.getString("ContNbr"), rs.getString("DisNm") , rs.getString("RoomNbr")});
        
        }
        
       }catch(Exception e){
       
             JOptionPane.showMessageDialog(rootPane, "failed" + e);
       }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPatntRgsSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_go;
    private javax.swing.JComboBox cmb_ptntslct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_rmpatntrgsrch;
    // End of variables declaration//GEN-END:variables

}
