
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import sun.java2d.pipe.SpanShapeRenderer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * patientcheckout.java
 *
 * Created on May 6, 2017, 12:04:04 PM
 */

/**
 *
 * @author PC 21
 */
public class frmPatientCheckout extends javax.swing.JFrame {

    /** Creates new form patientcheckout */
    public frmPatientCheckout() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        b_new = new javax.swing.JButton();
        b_firs = new javax.swing.JButton();
        b_prev = new javax.swing.JButton();
        b_sv = new javax.swing.JButton();
        b_updt = new javax.swing.JButton();
        b_nxt = new javax.swing.JButton();
        b_del = new javax.swing.JButton();
        b_lst = new javax.swing.JButton();
        t_chkotId = new javax.swing.JTextField();
        t_totDays = new javax.swing.JTextField();
        t_rmpr = new javax.swing.JTextField();
        t_msp = new javax.swing.JTextField();
        t_total = new javax.swing.JTextField();
        cmb_rmnbr = new javax.swing.JComboBox();
        cmb_patnm = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        t_dtin = new javax.swing.JTextField();
        b_calcdays = new javax.swing.JButton();
        t_dtout = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        b_calcamount = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Patient Checkout");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 32)); // NOI18N
        jLabel1.setText("Patient Checkout");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 270, 39);

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel2.setText("Checkout ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 120, 23);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel3.setText("Date In");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 80, 23);

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel4.setText("Total No. of Days");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 180, 23);

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel5.setText("Room No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 100, 23);

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel6.setText("Room Price");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 270, 103, 23);

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel8.setText("Medicine & Service Price");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 310, 220, 23);

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel9.setText("Total");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 350, 47, 23);

        b_new.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_new.setText("New");
        b_new.setOpaque(false);
        b_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_newActionPerformed(evt);
            }
        });
        getContentPane().add(b_new);
        b_new.setBounds(40, 390, 80, 29);

        b_firs.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_firs.setText("|<First");
        b_firs.setOpaque(false);
        b_firs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_firsActionPerformed(evt);
            }
        });
        getContentPane().add(b_firs);
        b_firs.setBounds(30, 440, 90, 29);

        b_prev.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_prev.setText("<<");
        b_prev.setOpaque(false);
        b_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_prevActionPerformed(evt);
            }
        });
        getContentPane().add(b_prev);
        b_prev.setBounds(170, 440, 71, 29);

        b_sv.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_sv.setText("Save");
        b_sv.setOpaque(false);
        b_sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_svActionPerformed(evt);
            }
        });
        getContentPane().add(b_sv);
        b_sv.setBounds(150, 390, 90, 29);

        b_updt.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_updt.setText("Update");
        b_updt.setOpaque(false);
        b_updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updtActionPerformed(evt);
            }
        });
        getContentPane().add(b_updt);
        b_updt.setBounds(270, 390, 100, 29);

        b_nxt.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_nxt.setText(">>");
        b_nxt.setOpaque(false);
        b_nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nxtActionPerformed(evt);
            }
        });
        getContentPane().add(b_nxt);
        b_nxt.setBounds(290, 440, 80, 29);

        b_del.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_del.setText("Delete");
        b_del.setOpaque(false);
        b_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_delActionPerformed(evt);
            }
        });
        getContentPane().add(b_del);
        b_del.setBounds(390, 390, 95, 29);

        b_lst.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_lst.setText("Last>|");
        b_lst.setOpaque(false);
        b_lst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lstActionPerformed(evt);
            }
        });
        getContentPane().add(b_lst);
        b_lst.setBounds(400, 440, 100, 29);

        t_chkotId.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_chkotId);
        t_chkotId.setBounds(250, 60, 190, 26);

        t_totDays.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_totDays);
        t_totDays.setBounds(250, 190, 190, 26);

        t_rmpr.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_rmpr);
        t_rmpr.setBounds(250, 270, 190, 26);

        t_msp.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_msp);
        t_msp.setBounds(250, 310, 190, 26);

        t_total.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_total);
        t_total.setBounds(250, 350, 190, 26);

        cmb_rmnbr.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        cmb_rmnbr.setModel(new DefaultComboBoxModel());
        cmb_rmnbr.setOpaque(false);
        cmb_rmnbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_rmnbrActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_rmnbr);
        cmb_rmnbr.setBounds(250, 230, 190, 26);

        cmb_patnm.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        cmb_patnm.setModel(new DefaultComboBoxModel());
        cmb_patnm.setOpaque(false);
        cmb_patnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_patnmActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_patnm);
        cmb_patnm.setBounds(250, 90, 190, 26);

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel10.setText("Patient Name");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 90, 130, 23);

        t_dtin.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_dtin);
        t_dtin.setBounds(250, 120, 190, 26);

        b_calcdays.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b_calcdays.setText("Calculate Days");
        b_calcdays.setOpaque(false);
        b_calcdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_calcdaysActionPerformed(evt);
            }
        });
        getContentPane().add(b_calcdays);
        b_calcdays.setBounds(440, 170, 120, 21);

        t_dtout.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_dtout);
        t_dtout.setBounds(250, 150, 190, 26);

        jLabel11.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel11.setText("Date Out");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 150, 81, 23);

        btnOk.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnOk.setText("Ok");
        btnOk.setOpaque(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(450, 90, 50, 21);

        b_calcamount.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b_calcamount.setText("Calculate Amount");
        b_calcamount.setOpaque(false);
        b_calcamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_calcamountActionPerformed(evt);
            }
        });
        getContentPane().add(b_calcamount);
        b_calcamount.setBounds(440, 310, 130, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAMSUNG\\Documents\\NetBeansProjects\\HMS\\HMS 28 dec\\HMS_&\\projct OMAGES\\patient checkout.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -20, 620, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    java.sql.Connection con = null;
   Statement stmt = null;
   Statement stmtpat = null;
   Statement stmtroom = null;   
   Statement stmtdate = null;   
   String dr = "java.sql.Driver";
   String url="jdbc:mysql://localhost:3306/hms?zeroDateTimeBehavior=convertToNull";
   String usr = "root";
   String pwd = "";
   String qry="";
   ResultSet rs = null;
   ResultSet rspat=null;
   ResultSet rsRoom=null;
   ResultSet rsdate=null;
   int rmid;           
   int patid;
   int msp,totl,rmprice;
   String RegDt;
           
   
    private void b_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_newActionPerformed
         // TODO add your handling code here:
      
        t_dtin.setText("");
        t_dtout.setText("");
        t_chkotId.setText("");
        t_totDays.setText("");
        t_rmpr.setText("");
        t_msp.setText("");
        t_total.setText("");
    
}//GEN-LAST:event_b_newActionPerformed

    private void b_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_prevActionPerformed
        // TODO add your handling code here:
       
        try{ 
            
            
        rs.previous();
        
        t_chkotId.setText(rs.getInt("ChkotID")+"");          
        t_dtin.setText(rs.getDate("RegDt")+"");
        t_dtout.setText(rs.getDate("DateOut")+"");       
        t_rmpr.setText(rs.getInt("RoomPrice")+"");
        t_msp.setText(rs.getInt("OtherMedSer")+"");
        t_total.setText(rs.getInt("TotalAmt")+"");
        
        
             
            
            
            
                
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(rootPane, "failed"+ e);
        }
        
}//GEN-LAST:event_b_prevActionPerformed

    private void b_svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_svActionPerformed
        // TODO add your handling code here:
         try {
           
           
            qry="select RoomID from roominfo where RoomNbr='"+cmb_rmnbr.getSelectedItem()+"'";
           rsRoom=stmtroom.executeQuery(qry);
           rsRoom.next();
          rmid=rsRoom.getInt("RoomID"); 
          
           qry="select PatID from registration where PatNm='"+cmb_patnm.getSelectedItem()+"'";
           rspat=stmtpat.executeQuery(qry);
           rspat.next();
          patid=rspat.getInt("PatID"); 
            
          msp=Integer.parseInt(t_msp.getText());
           
          totl=rmprice+msp;
          
          
          
            qry = "insert into checkout values("+patid+" , '"+RegDt+"' , '"+t_dtout.getText()+"' , "+rmid+" , "+rmprice+" , "+msp+" , "+totl+" )";
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(rootPane, "Records Saved Succesfully..!!!");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
    }//GEN-LAST:event_b_svActionPerformed

    private void b_updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updtActionPerformed
        // TODO add your handling code here:
        try {
           
            qry="select RoomID,RoomPrice from roominfo where RoomNbr='"+cmb_rmnbr.getSelectedItem()+"'";
           rsRoom=stmtroom.executeQuery(qry);
           rsRoom.next();
          rmid=rsRoom.getInt("RoomID"); 
          rmprice=rsRoom.getInt("RoomPrice");
          
          qry="select PatID,RegDt from registration where PatNm='"+cmb_patnm.getSelectedItem()+"'";
           rspat=stmtpat.executeQuery(qry);
           rspat.next();
          patid=rspat.getInt("PatID"); 
          RegDt=rspat.getDate("RegDt")+"";
          
          msp=Integer.parseInt(t_msp.getText());
           
          
          
            qry = "update checkout set RegDt='"+RegDt+"' , DateOut='"+t_dtout.getText()+"' , RoomID='"+rmid+"' , RoomPrice="+rmprice+" , OtherMedSer="+msp+" , TotalAmt="+t_total.getText()+"  where PatID="+patid;
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(rootPane, "record updated");


        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
}//GEN-LAST:event_b_updtActionPerformed

    private void b_nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nxtActionPerformed
        // TODO add your handling code here:
       
        try{  
        rs.next();
        
         t_chkotId.setText(rs.getInt("ChkotID")+"");       
        t_dtin.setText(rs.getDate("RegDt")+"");
        t_dtout.setText(rs.getDate("DateOut")+"");       
        t_rmpr.setText(rs.getInt("RoomPrice")+"");
        t_msp.setText(rs.getInt("OtherMedSer")+"");
        t_total.setText(rs.getInt("TotalAmt")+"");
        
        
             
          
                
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(rootPane, "failed"+ e);
        }
        
}//GEN-LAST:event_b_nxtActionPerformed

    private void b_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_delActionPerformed
        // TODO add your handling code here:
        try {
           
            
            
             qry="select PatID from registration where PatNm='"+cmb_patnm.getSelectedItem()+"'";
           rspat=stmtpat.executeQuery(qry);
           rspat.next();
          patid=rspat.getInt("PatID"); 
          
            qry = "delete from checkout where PatID="+patid;
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(rootPane, "record deleted");


        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
}//GEN-LAST:event_b_delActionPerformed

    private void b_lstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lstActionPerformed
        // TODO add your handling code here:
       
        
         try{  qry="select * from checkout";
            rs=stmt.executeQuery(qry);
        rs.last();
        
         t_chkotId.setText(rs.getInt("ChkotID")+"");       
        t_dtin.setText(rs.getDate("RegDt")+"");
        t_dtout.setText(rs.getDate("DateOut")+"");       
        t_rmpr.setText(rs.getInt("RoomPrice")+"");
        t_msp.setText(rs.getInt("OtherMedSer")+"");
        t_total.setText(rs.getInt("TotalAmt")+"");
        
        
        qry="select PatNm from Registration where PatId="+rs.getInt("PatID");
        rspat=stmtpat.executeQuery(qry);
        rspat.last();
        cmb_patnm.setSelectedItem(rspat.getString("PatNm"));
          
        
        qry="select RoomNbr,RoomPrice from roominfo where RoomID="+rs.getInt("RoomID");
           rsRoom=stmtroom.executeQuery(qry);
           rsRoom.last();
           cmb_rmnbr.setSelectedItem(rsRoom.getString("RoomNbr"));           
            t_rmpr.setText(rs.getInt("RoomPrice")+"");     
//            
                
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(rootPane, "failed"+ e);
        }
        
}//GEN-LAST:event_b_lstActionPerformed

    private void b_firsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_firsActionPerformed
        // TODO add your handling code here:
        
       try{ 
            
            qry="select * from checkout";
            rs=stmt.executeQuery(qry);
        rs.first();
        
        t_chkotId.setText(rs.getInt("ChkotID")+"");          
        t_dtin.setText(rs.getDate("RegDt")+"");
        t_dtout.setText(rs.getDate("DateOut")+"");       
        t_rmpr.setText(rs.getInt("RoomPrice")+"");
        t_msp.setText(rs.getInt("OtherMedSer")+"");
        t_total.setText(rs.getInt("TotalAmt")+"");
        
        
        qry="select PatNm from Registration where PatId="+rs.getInt("PatID");
        rspat=stmtpat.executeQuery(qry);
        rspat.first();
        cmb_patnm.setSelectedItem(rspat.getString("PatNm"));
          
        
        qry="select RoomNbr,RoomPrice from roominfo where RoomID="+rs.getInt("RoomID");
           rsRoom=stmtroom.executeQuery(qry);
           rsRoom.first();
           cmb_rmnbr.setSelectedItem(rsRoom.getString("RoomNbr"));           
            t_rmpr.setText(rs.getInt("RoomPrice")+"");     
//            
            
            
                
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(rootPane, "failed"+ e);
        }
    }//GEN-LAST:event_b_firsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setBounds(350, 120, 582, 510 );
        
       try{
          Class.forName(dr);
          con=DriverManager.getConnection(url, usr, pwd);
          stmt=con.createStatement();
          stmtpat=con.createStatement();
          stmtroom=con.createStatement();
          stmtdate=con.createStatement();
          
        DefaultComboBoxModel patnm_mdl=(DefaultComboBoxModel)cmb_patnm.getModel();
        DefaultComboBoxModel rmnbr_mdl=(DefaultComboBoxModel)cmb_rmnbr.getModel();
          
             qry="select PatNm from registration";
           rspat=stmtpat.executeQuery(qry);
           while(rspat.next())
               patnm_mdl.addElement(rspat.getString("PatNm"));
       
           qry="select RoomNbr from roominfo";
            rsRoom=stmtroom.executeQuery(qry);
            while(rsRoom.next())
                rmnbr_mdl.addElement(rsRoom.getString("RoomNbr"));
          
          
          
        qry="select * from checkout";
        rs=stmt.executeQuery(qry);
        rs.last();
        
        t_chkotId.setText(rs.getInt("ChkotID")+"");        
        t_dtin.setText(rs.getDate("RegDt")+"");
        t_dtout.setText(rs.getDate("DateOut")+"");       
        t_rmpr.setText(rs.getInt("RoomPrice")+"");
        t_msp.setText(rs.getInt("OtherMedSer")+"");
        t_total.setText(rs.getInt("TotalAmt")+"");
        
        qry="Select PatNm from Registration where PatID="+rs.getInt("PatID");
        rspat=stmtpat.executeQuery(qry);
        rspat.next();
        
        cmb_patnm.setSelectedItem(rspat.getString("PatNm"));
          
        
        qry="select RoomNbr,RoomPrice from roominfo where RoomID="+rs.getInt("RoomID");
        rsRoom=stmtroom.executeQuery(qry);
        rsRoom.next();
        cmb_rmnbr.setSelectedItem(rsRoom.getString("RoomNbr"));           
        t_rmpr.setText(rs.getInt("RoomPrice")+"");     

        
           
           
            
                 
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "failed"+ e);
        }
       
       
       
    }//GEN-LAST:event_formWindowOpened

    private void cmb_rmnbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_rmnbrActionPerformed
        // TODO add your handling code here:
        
         try{    
            
//            
//            String roomnbr="";
//                       
//                Class.forName(dr);
//                stmt=con.createStatement();
//                stmtroom=con.createStatement();
//                
//                roomnbr=cmb_rmnbr.getSelectedItem()+"";
//                
//                qry="select RoomPrice from roominfo where RoomNbr='"+roomnbr+"'";
//                rsRoom=stmtroom.executeQuery(qry);
//                rsRoom.next();
//                t_rmpr.setText(rsRoom.getInt("RoomPrice")+"");
                
        }catch(Exception e){JOptionPane.showMessageDialog(rootPane, "failed "+e);}
        
    }//GEN-LAST:event_cmb_rmnbrActionPerformed

    private void cmb_patnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_patnmActionPerformed
        // TODO add your handling code here:
        
          try{    
//            
//                String patnm;
//                Class.forName(dr);
//                stmt=con.createStatement();
//                stmtroom=con.createStatement();
//                
//                patnm=cmb_patnm.getSelectedItem()+"";
//                
//                
//               qry="select PatID,RegDt from registration where PatNm='"+patnm+"'" ;
//                rspat=stmtpat.executeQuery(qry);
//                rspat.next();
//                t_ptid.setText(rspat.getInt("PatID")+"");
//                t_dtin.setText(rspat.getDate("RegDt")+"");
//                
        }catch(Exception e){JOptionPane.showMessageDialog(rootPane, "failed "+e);}
        
    }//GEN-LAST:event_cmb_patnmActionPerformed

    private void b_calcdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_calcdaysActionPerformed
        // TODO add your handling code here:
        String DateIn,DateOut;
        Date D1,D2;
        SimpleDateFormat formatter=new SimpleDateFormat();
        DateIn=t_dtin.getText();
        DateOut=t_dtout.getText();
        
        int dayStart=Integer.parseInt(DateIn.substring(9));
        int dayEnd=Integer.parseInt(DateOut.substring(9));
        int NbrOfDays=dayEnd-dayStart;
        t_totDays.setText(NbrOfDays+"");
      
        
                
       
        
        
    }//GEN-LAST:event_b_calcdaysActionPerformed

    private void b_calcamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_calcamountActionPerformed
        // TODO add your handling code here:
        int days,roomprice,med,total;
        days=Integer.parseInt(t_totDays.getText());
        roomprice=Integer.parseInt(t_rmpr.getText());
       med=Integer.parseInt(t_msp.getText());
        total=med+(days*roomprice);
        t_total.setText(""+total);
    }//GEN-LAST:event_b_calcamountActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        try{    
                Class.forName(dr);
                stmtpat=con.createStatement();
                
                
                qry="select RegDt,PatID,RoomID from registration where PatNm='"+cmb_patnm.getSelectedItem().toString()+"'";
                rspat=stmtpat.executeQuery(qry);
                rspat.next();
                t_dtin.setText(rspat.getDate("RegDt")+"");
                
                qry="select RoomNbr,RoomPrice from roominfo where RoomID="+rspat.getInt("RoomID");
                rsRoom=stmtroom.executeQuery(qry);
                rsRoom.next();
                
                cmb_rmnbr.setSelectedItem(rsRoom.getString("RoomNbr"));
                t_rmpr.setText(rsRoom.getInt("RoomPrice")+"");

              
        }catch(Exception e){JOptionPane.showMessageDialog(rootPane, "failed "+e);}
        
    }//GEN-LAST:event_btnOkActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPatientCheckout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_calcamount;
    private javax.swing.JButton b_calcdays;
    private javax.swing.JButton b_del;
    private javax.swing.JButton b_firs;
    private javax.swing.JButton b_lst;
    private javax.swing.JButton b_new;
    private javax.swing.JButton b_nxt;
    private javax.swing.JButton b_prev;
    private javax.swing.JButton b_sv;
    private javax.swing.JButton b_updt;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cmb_patnm;
    private javax.swing.JComboBox cmb_rmnbr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t_chkotId;
    private javax.swing.JTextField t_dtin;
    private javax.swing.JTextField t_dtout;
    private javax.swing.JTextField t_msp;
    private javax.swing.JTextField t_rmpr;
    private javax.swing.JTextField t_totDays;
    private javax.swing.JTextField t_total;
    // End of variables declaration//GEN-END:variables

}
