
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lab5
 */
public class frmPatChkotSearch extends javax.swing.JFrame {

    /**
     * Creates new form frmPatChkotSearch
     */
    public frmPatChkotSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_dateout = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_patchkot = new javax.swing.JTable();
        b_go = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Patient Checkout Search");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Checkout");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 20, 330, 50);

        cmb_dateout.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cmb_dateout.setModel(new DefaultComboBoxModel());
        cmb_dateout.setOpaque(false);
        cmb_dateout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_dateoutActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_dateout);
        cmb_dateout.setBounds(290, 100, 188, 40);

        tbl_patchkot.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tbl_patchkot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Registration Date", "Date Out", "Room Number", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_patchkot.setOpaque(false);
        jScrollPane2.setViewportView(tbl_patchkot);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 170, 790, 210);

        b_go.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        b_go.setText("Go...!!!");
        b_go.setOpaque(false);
        b_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_goActionPerformed(evt);
            }
        });
        getContentPane().add(b_go);
        b_go.setBounds(560, 102, 146, 50);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel3.setText("Select Date ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 110, 171, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAMSUNG\\Documents\\NetBeansProjects\\HMS\\HMS 28 dec\\HMS_&\\projct OMAGES\\patchjkotsearch.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, -10, 870, 530);

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel4.setText("Select Date ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 110, 171, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
      Connection con=null;
    Statement stmt=null;
    Statement stmtpat=null;
    Statement stmtdate=null;
    String dr="java.sql.Driver";
    String url="jdbc:mysql://localhost:3306/hms?zeroDateTimeBehavior=convertToNull";
    String usr="root";
    String pwd="";
    String qry="";
    ResultSet rs=null;
    ResultSet rspat=null;
    ResultSet rsdate=null;
    int patid;
    private void b_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_goActionPerformed
        // TODO add your handling code here:

     
       
        try{

            DefaultTableModel tbl_mdl=(DefaultTableModel)tbl_patchkot.getModel();
          qry="select PatNm,Checkout.RegDt,DateOut,TotalAmt,RoomNbr from Checkout,Registration,RoomInfo where Checkout.RoomId=RoomInfo.RoomId and Checkout.PatId=Registration.PatId and DateOut='"+cmb_dateout.getSelectedItem()+"'";
          rs=stmt.executeQuery(qry);
          tbl_mdl.setRowCount(0);
          while(rs.next())
              tbl_mdl.addRow(new Object[]{rs.getString("PatNm"),rs.getDate("RegDt"),rs.getDate("DateOut"),rs.getString("RoomNbr"),rs.getInt("TotalAmt")});
          
        }catch(Exception e){

            JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }

    }//GEN-LAST:event_b_goActionPerformed

    private void cmb_dateoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_dateoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_dateoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setBounds(240, 120, 858, 507);
        
       try{
            Class.forName(dr);
            con=DriverManager.getConnection(url, usr, pwd);
            stmt=con.createStatement();
            stmtpat=con.createStatement();
            stmtdate=con.createStatement();
         
            
            
           qry="select DateOut from checkout";
           rsdate=stmtdate.executeQuery(qry);
           
           DefaultComboBoxModel cmdate_mdl=(DefaultComboBoxModel)cmb_dateout.getModel();
           
           while(rsdate.next())
                          cmdate_mdl.addElement(rsdate.getDate("DateOut"));
                      
          cmdate_mdl.insertElementAt("--Select--", 0);
          cmb_dateout.setSelectedIndex(0);
          
          DefaultTableModel tbl_mdl=(DefaultTableModel)tbl_patchkot.getModel();
          qry="select PatNm,Checkout.RegDt,DateOut,TotalAmt,RoomNbr from Checkout,Registration,RoomInfo where Checkout.RoomId=RoomInfo.RoomId and Checkout.PatId=Registration.PatId";
          rs=stmt.executeQuery(qry);
          
          while(rs.next())
              tbl_mdl.addRow(new Object[]{rs.getString("PatNm"),rs.getDate("RegDt"),rs.getDate("DateOut"),rs.getString("RoomNbr"),rs.getInt("TotalAmt")});
          
          
       
       }catch(Exception e){JOptionPane.showMessageDialog(rootPane, "failed"+e);}
        
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPatChkotSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPatChkotSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPatChkotSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPatChkotSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPatChkotSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_go;
    private javax.swing.JComboBox cmb_dateout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_patchkot;
    // End of variables declaration//GEN-END:variables
}
