
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_PatientRegistration.java
 *
 * Created on May 3, 2017, 11:49:54 AM
 */

/**
 *
 * @author PC 20
 */
public class frmPatientRegistration extends javax.swing.JFrame {

    /** Creates new form frm_PatientRegistration */
    public frmPatientRegistration() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_gndr = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        t_ptid = new javax.swing.JTextField();
        t_dtin = new javax.swing.JTextField();
        t_pnm = new javax.swing.JTextField();
        t_age = new javax.swing.JTextField();
        t_cno = new javax.swing.JTextField();
        t_disnm = new javax.swing.JTextField();
        t_distyp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_ad = new javax.swing.JTextArea();
        rd_ml = new javax.swing.JRadioButton();
        rd_fml = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        cmb_rmnbr = new javax.swing.JComboBox();
        cmb_rmtyp = new javax.swing.JComboBox();
        t_rmpri = new javax.swing.JTextField();
        b_up = new javax.swing.JButton();
        b_new = new javax.swing.JButton();
        b_sv = new javax.swing.JButton();
        b_prv = new javax.swing.JButton();
        b_frs = new javax.swing.JButton();
        b_lst = new javax.swing.JButton();
        b_nxt = new javax.swing.JButton();
        b_dlt = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Patient Registration");
        setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Registration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 312, 39);

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel2.setText("Patient ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 88, 23);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 41, 23);

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel4.setText("Patient Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 190, 119, 23);

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 240, 64, 23);

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel7.setText("Age");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 300, 33, 23);

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 380, 67, 23);

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel9.setText("Contact No.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 90, 108, 23);

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel10.setText("Type of Disease");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(480, 150, 138, 23);

        jLabel11.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel11.setText("Disease");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(480, 120, 64, 23);

        jLabel12.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel12.setText("Room Type");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(480, 230, 102, 23);

        jLabel13.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel13.setText("Room No");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(480, 190, 100, 23);

        jLabel14.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel14.setText("Price");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(480, 270, 44, 23);

        t_ptid.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_ptid);
        t_ptid.setBounds(200, 80, 157, 26);

        t_dtin.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_dtin);
        t_dtin.setBounds(200, 140, 157, 26);

        t_pnm.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_pnm);
        t_pnm.setBounds(200, 190, 157, 26);

        t_age.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_age);
        t_age.setBounds(200, 300, 157, 26);

        t_cno.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_cno);
        t_cno.setBounds(650, 90, 170, 26);

        t_disnm.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_disnm);
        t_disnm.setBounds(650, 120, 170, 26);

        t_distyp.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_distyp);
        t_distyp.setBounds(650, 150, 170, 26);

        t_ad.setColumns(20);
        t_ad.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        t_ad.setRows(5);
        jScrollPane1.setViewportView(t_ad);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 370, 340, 140);

        btngrp_gndr.add(rd_ml);
        rd_ml.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        rd_ml.setText("Male");
        rd_ml.setOpaque(false);
        getContentPane().add(rd_ml);
        rd_ml.setBounds(190, 240, 69, 31);

        btngrp_gndr.add(rd_fml);
        rd_fml.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        rd_fml.setText("Female");
        rd_fml.setOpaque(false);
        getContentPane().add(rd_fml);
        rd_fml.setBounds(310, 240, 87, 31);

        jLabel15.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel15.setText("(YYYY-MM-DD)");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(60, 140, 140, 23);

        cmb_rmnbr.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        cmb_rmnbr.setModel(new DefaultComboBoxModel());
        cmb_rmnbr.setOpaque(false);
        cmb_rmnbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_rmnbrActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_rmnbr);
        cmb_rmnbr.setBounds(650, 190, 171, 26);

        cmb_rmtyp.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        cmb_rmtyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Medium", "VIP" }));
        cmb_rmtyp.setOpaque(false);
        cmb_rmtyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_rmtypActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_rmtyp);
        cmb_rmtyp.setBounds(650, 230, 171, 26);

        t_rmpri.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_rmpri);
        t_rmpri.setBounds(650, 280, 166, 26);

        b_up.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_up.setText("Update");
        b_up.setOpaque(false);
        b_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_upActionPerformed(evt);
            }
        });
        getContentPane().add(b_up);
        b_up.setBounds(700, 370, 100, 29);

        b_new.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_new.setText("New");
        b_new.setOpaque(false);
        b_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_newActionPerformed(evt);
            }
        });
        getContentPane().add(b_new);
        b_new.setBounds(510, 370, 90, 29);

        b_sv.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_sv.setText("Save");
        b_sv.setOpaque(false);
        b_sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_svActionPerformed(evt);
            }
        });
        getContentPane().add(b_sv);
        b_sv.setBounds(610, 370, 80, 29);

        b_prv.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_prv.setText("<<");
        b_prv.setOpaque(false);
        b_prv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_prvActionPerformed(evt);
            }
        });
        getContentPane().add(b_prv);
        b_prv.setBounds(630, 430, 80, 29);

        b_frs.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_frs.setText("|<First");
        b_frs.setOpaque(false);
        b_frs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_frsActionPerformed(evt);
            }
        });
        getContentPane().add(b_frs);
        b_frs.setBounds(530, 430, 90, 29);

        b_lst.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_lst.setText("Last>|");
        b_lst.setOpaque(false);
        b_lst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lstActionPerformed(evt);
            }
        });
        getContentPane().add(b_lst);
        b_lst.setBounds(800, 430, 90, 29);

        b_nxt.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_nxt.setText(">>");
        b_nxt.setOpaque(false);
        b_nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nxtActionPerformed(evt);
            }
        });
        getContentPane().add(b_nxt);
        b_nxt.setBounds(720, 430, 70, 29);

        b_dlt.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_dlt.setText("Delete");
        b_dlt.setOpaque(false);
        b_dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dltActionPerformed(evt);
            }
        });
        getContentPane().add(b_dlt);
        b_dlt.setBounds(810, 370, 90, 29);

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(840, 190, 70, 23);

        jLabel17.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAMSUNG\\Documents\\NetBeansProjects\\HMS\\HMS 28 dec\\HMS_&\\projct OMAGES\\patientregistration.jpg")); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(-50, -10, 1050, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
Statement stmt=null;
Statement stmtroom=null;
String dr="java.sql.Driver";
String url="jdbc:mysql://localhost:3306/hms";
String usr="root";
String pwd="";
String qry="";
ResultSet rs=null;
String Gendr="";
ResultSet rsRoom=null;
int rmid;

    
    private void b_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_newActionPerformed
        // TODO add your handling code here:
          t_ptid.setText("");
        t_dtin.setText("");
        t_pnm.setText("");
        t_age.setText("");
        t_ad.setText("");
        t_cno.setText("");
        t_disnm.setText("");
        t_distyp.setText("");
        t_rmpri.setText("");
        btngrp_gndr.clearSelection();
        

    }//GEN-LAST:event_b_newActionPerformed

    private void b_svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_svActionPerformed
        // TODO add your handling code here:
  try{
     
     
      

        qry="select * from registration";
          rs=stmt.executeQuery(qry);
          
          

          
           qry="select RoomID from roominfo where RoomNbr='"+cmb_rmnbr.getSelectedItem()+"'";
           rsRoom=stmtroom.executeQuery(qry);
           rsRoom.next();
          rmid=rsRoom.getInt("RoomID");
       
        
         

 if(rd_fml.isSelected())
      {         Gendr="female";
      }
      else if(rd_ml.isSelected())
              {      Gendr="male";
              }
      





            qry="insert into registration values("+t_ptid.getText()+",'"+t_dtin.getText()+"' ,'"+t_pnm.getText()+"' ,'"+Gendr+"' ,"+ t_age.getText()+" ,'"+t_ad.getText() +"' ,'"+ t_cno.getText()+"','"+ t_disnm.getText()+"' ,'"+ t_distyp.getText()+"',"+rmid+")";
             stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(rootPane,"saved record ");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"falied"+"\n"+ e);
        }


        
    }//GEN-LAST:event_b_svActionPerformed

    private void b_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_upActionPerformed
        // TODO add your handling code here:

          try{
               
            qry="select RoomID from roominfo where RoomNbr='"+cmb_rmnbr.getSelectedItem()+"'";
            rsRoom=stmtroom.executeQuery(qry);
            rsRoom.next();
            rmid=rsRoom.getInt("RoomID");

            
            if(rd_fml.isSelected())
               Gendr="female";
      
            else if(rd_ml.isSelected())
                   Gendr="male";
              
            
        qry="update registration set RegDt='"+t_dtin.getText()+"' , PatNm='"+t_pnm.getText()+"' , Gndr='"+Gendr+"' , age="+ t_age.getText()+" , Addr='"+t_ad.getText() +"' , ContNbr='"+ t_cno.getText()+"', DisNm='"+ t_disnm.getText()+"' , Distyp='"+ t_distyp.getText()+"',RoomID="+rmid+" where PatID="+t_ptid.getText();
           stmt.executeUpdate(qry);
        JOptionPane.showMessageDialog(rootPane,"record updated");
        
        
        }
        catch(Exception e){JOptionPane.showMessageDialog(rootPane,"falied"+"\n"+ e);}


    }//GEN-LAST:event_b_upActionPerformed

    private void b_dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dltActionPerformed
        // TODO add your handling code here:

     try{


        qry="delete from registration where PatID="+t_ptid.getText();
        stmt.executeUpdate(qry);
         JOptionPane.showMessageDialog(rootPane,"record deleted");
         
       }                                                                  
        catch(Exception e){JOptionPane.showMessageDialog(rootPane,"failed"+"\n"+ e);}

         
    }//GEN-LAST:event_b_dltActionPerformed

    private void b_frsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_frsActionPerformed
        // TODO add your handling code here:


        try{ 
             
            rs.first();
        
                t_ptid.setText(rs.getInt("PatID")+"");
                  t_dtin.setText(rs.getDate("RegDt")+"");
                t_pnm.setText(rs.getString("PatNm"));
                
                
                if(rs.getString("Gndr").equals("male"))
                   rd_ml.setSelected(true);
               else if(rs.getString("Gndr").equals("female"))
                   rd_fml.setSelected(true); 
                
                t_age.setText(rs.getInt("age")+"");
                t_ad.append(rs.getString("Addr"));
                t_cno.setText(rs.getString("ContNbr"));
                t_disnm.setText(rs.getString("DisNm"));
                t_distyp.setText(rs.getString("Distyp"));      
                
                
              
                
                 qry="select RoomNbr,RoomTyp,RoomPrice from roominfo where RoomID="+rs.getInt("RoomID");
           rsRoom=stmtroom.executeQuery(qry);
           rsRoom.next();
           cmb_rmnbr.setSelectedItem(rsRoom.getString("RoomNbr"));
           cmb_rmtyp.setSelectedItem(rsRoom.getString("RoomTyp"));
            t_rmpri.setText(rsRoom.getInt("RoomPrice")+"");    
                
                
                            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
    }//GEN-LAST:event_b_frsActionPerformed

    private void b_prvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_prvActionPerformed
        // TODO add your handling code here:\
               
             try{  
          
            rs.previous();
        
                t_ptid.setText(rs.getInt("PatID")+"");
                   t_dtin.setText(rs.getDate("RegDt")+"");
                t_pnm.setText(rs.getString("PatNm"));
                
                 if(rs.getString("Gndr").equals("male"))
                   rd_ml.setSelected(true);
               else if(rs.getString("Gndr").equals("female"))
                   rd_fml.setSelected(true);    
                 
                t_age.setText(rs.getInt("age")+"");
                t_ad.append(rs.getString("Addr"));
                t_cno.setText(rs.getString("ContNbr"));
                t_disnm.setText(rs.getString("DisNm"));
                t_distyp.setText(rs.getString("Distyp"));
                    
                
                
                 qry="select RoomNbr,RoomTyp,RoomPrice from roominfo where RoomID="+rs.getInt("RoomID");
           rsRoom=stmtroom.executeQuery(qry);
           rsRoom.next();
           cmb_rmnbr.setSelectedItem(rsRoom.getString("RoomNbr"));
           cmb_rmtyp.setSelectedItem(rsRoom.getString("RoomTyp"));
            t_rmpri.setText(rsRoom.getInt("RoomPrice")+"");    
                
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
    }//GEN-LAST:event_b_prvActionPerformed

    private void b_nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nxtActionPerformed
        // TODO add your handling code here:

         try{ 
                
          
            rs.next();
        
                t_ptid.setText(rs.getInt("PatID")+"");
                   t_dtin.setText(rs.getDate("RegDt")+"");
                t_pnm.setText(rs.getString("PatNm"));
                
                 if(rs.getString("Gndr").equals("male"))
                   rd_ml.setSelected(true);
               else if(rs.getString("Gndr").equals("female"))
                   rd_fml.setSelected(true);    
                 
                t_age.setText(rs.getInt("age")+"");
                t_ad.append(rs.getString("Addr"));
                t_cno.setText(rs.getString("ContNbr"));
                t_disnm.setText(rs.getString("DisNm"));
                t_distyp.setText(rs.getString("Distyp"));
                     
                
                
                
                
                 qry="select RoomNbr,RoomTyp,RoomPrice from roominfo where RoomID="+rs.getInt("RoomID");
           rsRoom=stmtroom.executeQuery(qry);
           rsRoom.next();
           cmb_rmnbr.setSelectedItem(rsRoom.getString("RoomNbr"));
           cmb_rmtyp.setSelectedItem(rsRoom.getString("RoomTyp"));
            t_rmpri.setText(rsRoom.getInt("RoomPrice")+"");    
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
    }//GEN-LAST:event_b_nxtActionPerformed

    private void b_lstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lstActionPerformed
        // TODO add your handling code here:

          
            
          try{ 
               
          
            rs.last();
        
                t_ptid.setText(rs.getInt("PatID")+"");
                   t_dtin.setText(rs.getDate("RegDt")+"");
                t_pnm.setText(rs.getString("PatNm"));
                
                 if(rs.getString("Gndr").equals("male"))
                   rd_ml.setSelected(true);
               else if(rs.getString("Gndr").equals("female"))
                   rd_fml.setSelected(true);    
                 
                t_age.setText(rs.getInt("age")+"");
                t_ad.append(rs.getString("Addr"));
                t_cno.setText(rs.getString("ContNbr"));
                t_disnm.setText(rs.getString("DisNm"));
                t_distyp.setText(rs.getString("Distyp"));
               
                
                
                
                 qry="select RoomNbr,RoomTyp,RoomPrice from roominfo where RoomID="+rs.getInt("RoomID");
           rsRoom=stmtroom.executeQuery(qry);
           rsRoom.next();
           cmb_rmnbr.setSelectedItem(rsRoom.getString("RoomNbr"));
           cmb_rmtyp.setSelectedItem(rsRoom.getString("RoomTyp"));
            t_rmpri.setText(rsRoom.getInt("RoomPrice")+"");    
            
                         
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
    }//GEN-LAST:event_b_lstActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         this.setBounds(240, 120, 939 ,588);
        
          try{
          Class.forName(dr);
          con=DriverManager.getConnection(url, usr, pwd);
          stmt=con.createStatement();
         
          
            qry="select RoomNbr from roominfo";
          stmtroom=con.createStatement();
          rsRoom=stmtroom.executeQuery(qry);
                      DefaultComboBoxModel rmnbr_mdl=(DefaultComboBoxModel)cmb_rmnbr.getModel();
                while(rsRoom.next())
                    rmnbr_mdl.addElement(rsRoom.getString("RoomNbr"));
                
          
          qry="select * from registration";
          rs=stmt.executeQuery(qry);
          
          rs.last();
        
          t_ptid.setText(rs.getInt("PatID")+"");
          t_dtin.setText(rs.getDate("RegDt")+"");
          t_pnm.setText(rs.getString("PatNm"));
         
          Gendr=rs.getString("Gndr");
                
          if(Gendr.equals("male"))
                rd_ml.setSelected(true);
          else if(Gendr.equals("female"))
                rd_fml.setSelected(true);    
                 
           t_age.setText(rs.getInt("age")+"");  
           t_ad.append(rs.getString("Addr"));
           t_cno.setText(rs.getString("ContNbr"));
           t_disnm.setText(rs.getString("DisNm"));
           t_distyp.setText(rs.getString("Distyp"));       
           
          
           
       
      
           
                
        
           qry="select RoomNbr,RoomTyp,RoomPrice from roominfo where RoomID="+rs.getInt("RoomID");
           rsRoom=stmtroom.executeQuery(qry);
           rsRoom.next();
           cmb_rmnbr.setSelectedItem(rsRoom.getString("RoomNbr"));
           cmb_rmtyp.setSelectedItem(rsRoom.getString("RoomTyp"));
            t_rmpri.setText(rsRoom.getInt("RoomPrice")+"");       
             
            
                
                
       }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
          
          
        
    }//GEN-LAST:event_formWindowOpened

    private void cmb_rmnbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_rmnbrActionPerformed
        // TODO add your handling code here:
        

        
        
        
    }//GEN-LAST:event_cmb_rmnbrActionPerformed

    private void cmb_rmtypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_rmtypActionPerformed
        // TODO add your handling code here:
        
//        if(cmb_rmtyp.getSelectedItem().equals("Normal"))
//        {
//            t_rmpri.setText(3000+"");
//        }
//        else if(cmb_rmtyp.getSelectedItem().equals("Medium"))
//        {
//            t_rmpri.setText(4000+"");
//        }
//        else if(cmb_rmtyp.getSelectedItem().equals("VIP"))
//        {
//            t_rmpri.setText(5000+"");
//        }
    }//GEN-LAST:event_cmb_rmtypActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
                 try{    
                Class.forName(dr);
                stmtroom=con.createStatement();
                
                
                qry="select RoomTyp,RoomPrice from roominfo where RoomNbr='"+cmb_rmnbr.getSelectedItem().toString()+"'";
                rsRoom=stmtroom.executeQuery(qry);
                rsRoom.next();
                
                cmb_rmtyp.setSelectedItem(rsRoom.getString("RoomTyp"));
                t_rmpri.setText(rsRoom.getInt("RoomPrice")+"");
                
        }catch(Exception e){JOptionPane.showMessageDialog(rootPane, "failed "+e);}
        
    }//GEN-LAST:event_btnOkActionPerformed



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPatientRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_dlt;
    private javax.swing.JButton b_frs;
    private javax.swing.JButton b_lst;
    private javax.swing.JButton b_new;
    private javax.swing.JButton b_nxt;
    private javax.swing.JButton b_prv;
    private javax.swing.JButton b_sv;
    private javax.swing.JButton b_up;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup btngrp_gndr;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmb_rmnbr;
    private javax.swing.JComboBox cmb_rmtyp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rd_fml;
    private javax.swing.JRadioButton rd_ml;
    private javax.swing.JTextArea t_ad;
    private javax.swing.JTextField t_age;
    private javax.swing.JTextField t_cno;
    private javax.swing.JTextField t_disnm;
    private javax.swing.JTextField t_distyp;
    private javax.swing.JTextField t_dtin;
    private javax.swing.JTextField t_pnm;
    private javax.swing.JTextField t_ptid;
    private javax.swing.JTextField t_rmpri;
    // End of variables declaration//GEN-END:variables

}
