
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmRoomInfoSearch.java
 *
 * Created on May 10, 2017, 11:55:58 AM
 */

/**
 *
 * @author PC 20
 */
public class frmRoomInfoSearch extends javax.swing.JFrame {

    /** Creates new form frmRoomInfoSearch */
    public frmRoomInfoSearch() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_rmslct = new javax.swing.JComboBox();
        b_go = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rminfo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Room Information Search");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel1.setText("Select Room");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 30, 171, 30);

        cmb_rmslct.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        cmb_rmslct.setOpaque(false);
        getContentPane().add(cmb_rmslct);
        cmb_rmslct.setBounds(110, 100, 188, 43);

        b_go.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        b_go.setText("Go...!!!");
        b_go.setOpaque(false);
        b_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_goActionPerformed(evt);
            }
        });
        getContentPane().add(b_go);
        b_go.setBounds(560, 70, 146, 72);

        tbl_rminfo.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        tbl_rminfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No.", "Type", "Bed", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_rminfo.setOpaque(false);
        jScrollPane1.setViewportView(tbl_rminfo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 190, 559, 346);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 600);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAMSUNG\\Documents\\NetBeansProjects\\HMS\\HMS 28 dec\\HMS_&\\projct OMAGES\\omega-multispeciality-hospital-bangalore-1466152045-5763b46d7163f.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 920, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection con=null;
    Statement stmt=null;
    String dr="java.sql.Driver";
   String url="jdbc:mysql://localhost:3306/hms?zeroDateTimeBehavior=convertToNull";
    String usr="root";
    String pwd="";
    String qry="";
    ResultSet rs=null;
    private void b_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_goActionPerformed
        // TODO add your handling code here:            ////room nos is 100s

         try{
             
             Class.forName(dr);
             con=DriverManager.getConnection(url, usr, pwd);
             stmt=con.createStatement();
          qry="select RoomID, RoomTyp, NbrofBed, RoomPrice from RoomInfo where RoomID='"+cmb_rmslct.getSelectedItem()+"'";
        rs=stmt.executeQuery(qry);
        
        while(rs.next())
       {
         DefaultTableModel mdl=(DefaultTableModel)tbl_rminfo.getModel();
        mdl.addRow(new Object[]{ rs.getInt("RoomID"), rs.getString("RoomTyp"), rs.getString("NbrofBed"), rs.getString("RoomPrice")  });
       }
         }catch(Exception e){
                
             JOptionPane.showMessageDialog(rootPane, "failed" + e);
       }
    }//GEN-LAST:event_b_goActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setBounds(250, 120, 898, 600);
        
        try{
             
             Class.forName(dr);
             con=DriverManager.getConnection(url, usr, pwd);
             stmt=con.createStatement();
          qry="select RoomID, RoomTyp, NbrofBed, RoomPrice from RoomInfo";
        rs=stmt.executeQuery(qry);
        
        while (rs.next())
        {
            DefaultComboBoxModel cmdl=(DefaultComboBoxModel)cmb_rmslct.getModel();
            cmdl.addElement(rs.getString("RoomId")+"");
        
        }
        
        while(rs.next())
       {
         DefaultTableModel mdl=(DefaultTableModel)tbl_rminfo.getModel();
        mdl.addRow(new Object[]{ rs.getInt("RoomID"), rs.getString("RoomTyp"), rs.getString("NbrofBed"), rs.getString("RoomPrice")  });
        
        }
        
       }catch(Exception e){
       
             JOptionPane.showMessageDialog(rootPane, "failed" + e);
       }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRoomInfoSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_go;
    private javax.swing.JComboBox cmb_rmslct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_rminfo;
    // End of variables declaration//GEN-END:variables

}
