
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmroominfo.java
 *
 * Created on May 3, 2017, 11:45:34 AM
 */

/**
 *
 * @author PC 21
 */
public class frmRoomInfo extends javax.swing.JFrame {

    /** Creates new form frmroominfo */
    public frmRoomInfo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        b_sv = new javax.swing.JButton();
        b_new = new javax.swing.JButton();
        b_upd = new javax.swing.JButton();
        b_delt = new javax.swing.JButton();
        t_rmprice = new javax.swing.JTextField();
        b_fir = new javax.swing.JButton();
        b_lst = new javax.swing.JButton();
        b_nxt = new javax.swing.JButton();
        b_prev = new javax.swing.JButton();
        cmb_rmtyp = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        t_rmid = new javax.swing.JTextField();
        t_rmnbr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Room Information");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 32)); // NOI18N
        jLabel1.setText("Room Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 40, 310, 39);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel3.setText("Room Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 150, 130, 23);

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel4.setText("Room Type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 102, 23);

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel6.setText("Price");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 230, 44, 23);

        b_sv.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_sv.setText("Save");
        b_sv.setOpaque(false);
        b_sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_svActionPerformed(evt);
            }
        });
        getContentPane().add(b_sv);
        b_sv.setBounds(170, 350, 80, 29);

        b_new.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_new.setText("New");
        b_new.setOpaque(false);
        b_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_newActionPerformed(evt);
            }
        });
        getContentPane().add(b_new);
        b_new.setBounds(60, 350, 80, 29);

        b_upd.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_upd.setText("Update");
        b_upd.setOpaque(false);
        b_upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updActionPerformed(evt);
            }
        });
        getContentPane().add(b_upd);
        b_upd.setBounds(279, 350, 100, 29);

        b_delt.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_delt.setText("Delete");
        b_delt.setOpaque(false);
        b_delt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deltActionPerformed(evt);
            }
        });
        getContentPane().add(b_delt);
        b_delt.setBounds(400, 350, 100, 29);

        t_rmprice.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_rmprice);
        t_rmprice.setBounds(320, 240, 180, 26);

        b_fir.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_fir.setText("|<First");
        b_fir.setOpaque(false);
        b_fir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_firActionPerformed(evt);
            }
        });
        getContentPane().add(b_fir);
        b_fir.setBounds(50, 410, 100, 29);

        b_lst.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_lst.setText("Last>|");
        b_lst.setOpaque(false);
        b_lst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lstActionPerformed(evt);
            }
        });
        getContentPane().add(b_lst);
        b_lst.setBounds(420, 410, 100, 29);

        b_nxt.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_nxt.setText(">>");
        b_nxt.setOpaque(false);
        b_nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nxtActionPerformed(evt);
            }
        });
        getContentPane().add(b_nxt);
        b_nxt.setBounds(300, 410, 89, 29);

        b_prev.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        b_prev.setText("<<");
        b_prev.setOpaque(false);
        b_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_prevActionPerformed(evt);
            }
        });
        getContentPane().add(b_prev);
        b_prev.setBounds(190, 410, 77, 29);

        cmb_rmtyp.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        cmb_rmtyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Medium", "VIP" }));
        cmb_rmtyp.setOpaque(false);
        getContentPane().add(cmb_rmtyp);
        cmb_rmtyp.setBounds(320, 190, 180, 26);

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel8.setText("Room ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 100, 79, 23);

        t_rmid.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_rmid);
        t_rmid.setBounds(320, 100, 180, 26);

        t_rmnbr.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        getContentPane().add(t_rmnbr);
        t_rmnbr.setBounds(320, 150, 180, 26);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAMSUNG\\Documents\\NetBeansProjects\\HMS\\HMS 28 dec\\HMS_&\\projct OMAGES\\roominfo.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-130, 0, 770, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     java.sql.Connection con = null;
   Statement stmt = null;
   ResultSet rs = null;
   String dr = "java.sql.Driver";
   String url="jdbc:mysql://localhost:3306/hms?zeroDateTimeBehavior=convertToNull";
   String usr = "root";
   String pwd = "";
   String qry="";
    private void b_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_newActionPerformed
        // TODO add your handling code here:
        

     t_rmid.setText("");
     t_rmnbr.setText("");           
        t_rmprice.setText("");
    }//GEN-LAST:event_b_newActionPerformed

    private void b_svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_svActionPerformed
        // TODO add your handling code here:
      try {
         
        qry = "insert into roominfo values("+t_rmid.getText()+"  ,'"+t_rmnbr.getText()+"' , '"+cmb_rmtyp.getSelectedItem()+"' ,  "+t_rmprice.getText()+") ";
           stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(rootPane, "record saved");

        } catch (Exception e) {

        JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }

    }//GEN-LAST:event_b_svActionPerformed

    private void b_updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updActionPerformed
        // TODO add your handling code here:
        try {
    
            qry = "update roominfo set  RoomNbr='"+t_rmnbr.getText()+"' , RoomTyp='"+cmb_rmtyp.getSelectedItem()+"' ,  RoomPrice="+t_rmprice.getText()+" where RoomID="+t_rmid.getText()+"";
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(rootPane, "record updated");


        } catch (Exception e) {

        JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
    }//GEN-LAST:event_b_updActionPerformed

    private void b_deltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deltActionPerformed
        // TODO add your handling code here:
        try {
       
            qry = "delete from roominfo where RoomID="+t_rmid.getText()+"";           
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(rootPane, "record deleted");


        } catch (Exception e) {

        JOptionPane.showMessageDialog(rootPane, "failed " + e);
        
        }
    }//GEN-LAST:event_b_deltActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        this.setBounds(380, 120,583, 529);

          try{
          Class.forName(dr);
          con=DriverManager.getConnection(url, usr, pwd);
          stmt=con.createStatement();
          qry="select * from roominfo";          
          rs=stmt.executeQuery(qry);
          
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "failed" + e);
            }
          
           try{ 
             
             rs.last();
                   
                 t_rmid.setText(rs.getInt("RoomID")+"");  
                 t_rmnbr.setText(rs.getString("RoomNbr")+"");                 
                 cmb_rmtyp.setSelectedItem(rs.getString("RoomTyp")+"");
                 t_rmprice.setText(rs.getInt("RoomPrice")+"");  

        }catch(Exception e){
        
         JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void b_lstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lstActionPerformed
        // TODO add your handling code here:
        try{ 
             
             rs.last();
                   t_rmid.setText(rs.getInt("RoomID")+"");  
                 t_rmnbr.setText(rs.getString("RoomNbr")+"");                 
                 cmb_rmtyp.setSelectedItem(rs.getString("RoomTyp")+"");
                 t_rmprice.setText(rs.getInt("RoomPrice")+"");   

        }catch(Exception e){
        
         JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
    }//GEN-LAST:event_b_lstActionPerformed

    private void b_nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nxtActionPerformed
        // TODO add your handling code here:
        try{  
            rs.next();
              t_rmid.setText(rs.getInt("RoomID")+"");  
                 t_rmnbr.setText(rs.getString("RoomNbr")+"");                 
                 cmb_rmtyp.setSelectedItem(rs.getString("RoomTyp")+"");
                 t_rmprice.setText(rs.getInt("RoomPrice")+"");  
                 
                 
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
    }//GEN-LAST:event_b_nxtActionPerformed

    private void b_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_prevActionPerformed
        // TODO add your handling code here:
        
          try{  
              rs.previous();
                t_rmid.setText(rs.getInt("RoomID")+"");  
                 t_rmnbr.setText(rs.getString("RoomNbr")+"");                 
                 cmb_rmtyp.setSelectedItem(rs.getString("RoomTyp")+"");
                 t_rmprice.setText(rs.getInt("RoomPrice")+"");  
                 
        }catch(Exception e){
        
         JOptionPane.showMessageDialog(rootPane, "failed" + e);
        }
    }//GEN-LAST:event_b_prevActionPerformed

    private void b_firActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_firActionPerformed
        // TODO add your handling code here:
        
         try{
               
               rs.first();
                 t_rmid.setText(rs.getInt("RoomID")+"");  
                 t_rmnbr.setText(rs.getString("RoomNbr")+"");                 
                 cmb_rmtyp.setSelectedItem(rs.getString("RoomTyp")+"");
                 t_rmprice.setText(rs.getInt("RoomPrice")+"");  

        }catch(Exception e){
        
        JOptionPane.showMessageDialog(rootPane,  "failed" + e);
        }
    }//GEN-LAST:event_b_firActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRoomInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_delt;
    private javax.swing.JButton b_fir;
    private javax.swing.JButton b_lst;
    private javax.swing.JButton b_new;
    private javax.swing.JButton b_nxt;
    private javax.swing.JButton b_prev;
    private javax.swing.JButton b_sv;
    private javax.swing.JButton b_upd;
    private javax.swing.JComboBox cmb_rmtyp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField t_rmid;
    private javax.swing.JTextField t_rmnbr;
    private javax.swing.JTextField t_rmprice;
    // End of variables declaration//GEN-END:variables

}
